warning_days: 21
domains:
  - bcr.bazel.build
  - registry.bazel.build
  - be.bazel.build
  - blog.bazel.build
  - ci.bazel.build
  - cr.bazel.build
  - cs.bazel.build
  - dashboard.bazel.build
  - docs.bazel.build
  - ij.bazel.build
  - mirror.bazel.build
  - perf.bazel.build
  - releases.bazel.build
  - skydoc.bazel.build
  - tulsi.bazel.build
