destination: production
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  toc_levels: "2,3"
highlighter: rouge

paginate: 10
sass:
  sass_dir: _sass
gems:
  - jekyll-paginate
  - jekyll-toc
  - jekyll-sitemap

url: "https://docs.bazel.build" # used by jekyll-sitemap

# Update this to the newest release for the default docs.bazel.build version.
version: "4.0.0"

# This must be kept in sync with //scripts/docs:doc_versions.bzl
doc_versions:
  - master
  - 4.0.0
  - 3.7.0
  - 3.6.0
  - 3.5.1
  - 3.4.0
  - 3.3.0
  - 3.2.0
  - 3.1.0
  - 3.0.0
  - 2.2.0
  - 2.1.0
  - 2.0.0
  - 1.2.0
  - 1.1.0
  - 1.0.0
  - 0.29.1
  - 0.29.0
  - 0.28.0
  - 0.27.0
  - 0.26.0
  - 0.25.0
  - 0.24.0
  - 0.23.0
  - 0.22.0
  - 0.21.0
  - 0.20.0
  - 0.19.2
  - 0.19.1
  - 0.18.1
  - 0.17.2
  - 0.17.1

main_site_url: https://www.bazel.build
getting_started_category_url: "/bazel-overview.html"
docs_site_url: "/guide.html"
extending_category_url: "/skylark/concepts.html"
blog_site_url: https://blog.bazel.build

defaults:
  # Enable table of contents for every page
  -
    scope:
      path: ""
    values:
      toc: true
      sitemap: true
  -
    scope:
      type: "pages"
    values:
      category: "documentation"

# jekyll-toc settings
toc:
  min_level: 2
  max_level: 3
  list_class: page-toc
  sublist_class: page-toc-sublist
