destination: production
markdown: redcarpet
paginate: 10
highlighter: pygments
sass:
  sass_dir: _sass
gems: [jekyll-paginate]

version: "master"

main_site_url: https://www.bazel.build
blog_site_url: https://blog.bazel.build
