name: cherry-picker

on:
  pull_request:
    types: [closed]
    branches: [master]
  issues:
    types: [closed, milestoned]

permissions:
  contents: read

env:
  GH_TOKEN: ${{ secrets.BAZEL_IO_TOKEN }}

jobs:
  cherry-picker-on-closed:
    if: github.event.action == 'closed' && github.event.sender.login == 'copybara-service[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7
        with:
          egress-policy: audit
      - if: github.event.pull_request
        name: Run cherrypicker on closed PR
        uses: bazelbuild/continuous-integration/actions/cherry_picker@312ab25f6994b2fac89dc6910b3ebd6cb93cfa74
        with:
          triggered-on: closed
          pr-number: ${{ github.event.number }}
          is-prod: True
      - if: github.event.issue
        name: Run cherrypicker on closed issue
        uses: bazelbuild/continuous-integration/actions/cherry_picker@312ab25f6994b2fac89dc6910b3ebd6cb93cfa74
        with:
          triggered-on: closed
          pr-number: ${{ github.event.issue.number }}
          is-prod: True
  cherry-picker-on-milestoned:
    if: github.event.action == 'milestoned'
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7
        with:
          egress-policy: audit
      - if: startsWith(github.event.issue.body, 'Forked from')
        name: Run cherrypicker on comment
        uses: bazelbuild/continuous-integration/actions/cherry_picker@312ab25f6994b2fac89dc6910b3ebd6cb93cfa74
        with:
          triggered-on: commented
          pr-number: ${{ github.event.issue.body }}
          milestone-title: ${{ github.event.milestone.title }}
          milestoned-issue-number: ${{ github.event.issue.number }}
          is-prod: True
      - if: startsWith(github.event.issue.body, '### Commit IDs')
        name: Run cherrypicker on demand
        uses: bazelbuild/continuous-integration/actions/cherry_picker@312ab25f6994b2fac89dc6910b3ebd6cb93cfa74
        with:
          triggered-on: ondemand
          milestone-title: ${{ github.event.milestone.title }}
          milestoned-issue-number: ${{ github.event.issue.number }}
          issue-title: ${{ github.event.issue.title }}
          issue-body: ${{ github.event.issue.body }}
          is-prod: True
